# -----------------------------------------
# Environment (MISMO QUE TRAIN)
# -----------------------------------------
environment:
  grid:
    - [0,0,0,0,0,0,0,0]
    - [0,1,1,1,0,1,1,0]
    - [0,0,0,1,0,0,1,0]
    - [1,1,0,0,0,1,0,0]
    - [0,0,0,1,0,0,0,1]
    - [0,1,0,0,0,1,0,0]
    - [0,1,0,1,0,0,0,0]
    - [0,0,0,0,1,1,0,0]

  random_start_goal: true
  max_steps: 200 # Modelo 2.7.3
  render: false


# -----------------------------------------
# Evaluation
# -----------------------------------------
evaluation:
  num_episodes: 200
  max_steps_per_episode: 200 # Modelo 2.7.3
  seed: 123


# -----------------------------------------
# Paths
# -----------------------------------------
paths:
  checkpoint_dir: results/checkpoints
  results_path: results/checkpoint_evaluation.json
