environment:
  grid:
    - [0, 0, 0, 0, 0]
    - [0, 1, 1, 1, 0]
    - [0, 0, 0, 1, 0]
    - [1, 1, 0, 0, 0]
    - [0, 0, 0, 1, 0]

  start: [0, 0]
  goal: [4, 4]

  max_steps: 100
  render: false

agent:
  type: dqn
  epsilon: 0.0   # greedy puro

model:
  path: results/best_model/best_model.pth

seed: 123
